# Uncomment the next line to define a global platform for your project
platform :osx, '10.9'
use_frameworks!
target 'SULUserNotificationCenterExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'SULUserNotificationCenter' , :path => '../'

  # Pods for SULUserNotificationCenterExample

  target 'SULUserNotificationCenterExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
